// <auto-generated />
namespace SGRE.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class InicialCreacionTablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicialCreacionTablas));
        
        string IMigrationMetadata.Id
        {
            get { return "202608210527437_InicialCreacionTablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
